### ISSUE TITLE
ReUseModel->TestFAEModel.py

### ISSUE THREAD

**Issue by liuwenhaha** [salan668/FAE#48]
我用得是example文件夹里的原始数据，但是训练完模型以后，想测试数据，报错了。
使用Norm0Center_PCC_ANOVA_20_SVM，这是一种错误：
Traceback (most recent call last):
  File "E:/FAE-master/ReUseModel/TestFAEModel.py", line 112, in <module>
    r'E:\FAE-master\demo')
  File "E:/FAE-master/ReUseModel/TestFAEModel.py", line 67, in TestNewData
    new_data_container = train_info['normalizer'].Transform(new_data_container)
  File "E:\FAE-master\FAE\FeatureAnalysis\Normalizer.py", line 14, in Transform
    array -= self._interception
ValueError: operands could not be broadcast together with shapes (78,20) (261,) (78,20) 
使用Norm0Center_PCA_ANOVA_20_SVM，这又是一种错误：
KeyError: "None of [Index(['PCA_feature_1', 'PCA_feature_2', 'PCA_feature_3', 'PCA_feature_5',\n       'PCA_feature_6', 'PCA_feature_8', 'PCA_feature_9', 'PCA_feature_10',\n       'PCA_feature_14', 'PCA_feature_19', 'PCA_feature_27', 'PCA_feature_31',\n       'PCA_feature_50', 'PCA_feature_63', 'PCA_feature_66', 'PCA_feature_97',\n       'PCA_feature_120', 'PCA_feature_124', 'PCA_feature_181',\n       'PCA_feature_182'],\n      dtype='object')] are in the [columns]"

**Comment by salan668** [comment]
谢谢您的问题。

目前TestFAEMode还是未经过测试代码，我们还未没有将其整合到FAE的主要程序中。FAE是基于scikit-learn进行搭建，其模型您可以使用sklearn的相关功能进行模型加载。

如果希望我们这边帮忙解决，不知能否将您训练出来的模型、相关代码、以及数据打包发给我们？我们进行本地测试，并更新相关代码？

谢谢

**Comment by liuwenhaha** [comment]
> 谢谢您的问题。
> 
> 目前TestFAEMode还是未经过测试代码，我们还未没有将其整合到FAE的主要程序中。FAE是基于scikit-learn进行搭建，其模型您可以使用sklearn的相关功能进行模型加载。
> 
> 如果希望我们这边帮忙解决，不知能否将您训练出来的模型、相关代码、以及数据打包发给我们？我们进行本地测试，并更新相关代码？
> 
> 谢谢

我用的就是fork以后example文件夹自带的numeric_feature.csv，分类方法用svm，按照你们的指导说明操作了一遍，所有都一样的。我看见ReUseModel文件夹里的TestFAEModel.py，可以加载模型预测就想试试，但是报错了，最后我改了一下没成功就找你们了
